name: timeismoney
description: Application ludique et utilitaire pour visualiser en temps réel l'argent que l'on gagne.
publish_to: 'none'
version: 1.4.5+191025

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Pour la localisation
    sdk: flutter
  lottie: ^2.4.0
  flutter_lints: ^2.0.0
  intl: 0.20.2
  package_info_plus: ^4.0.0

  # Vos dépendances de packages
  provider: ^6.1.1 
  shared_preferences: ^2.3.2
  http: ^1.1.0 # Pour récupérer les taux de change
  url_launcher: ^6.2.0 # Pour ouvrir des URLs dans le navigateur
  flutter_local_notifications: ^17.2.2 # Pour les notifications locales

  # Optional: if you want to render SVG assets directly in Flutter widgets
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# ----------------------------------------------------
#  NOUVELLE SECTION ET EMPLACEMENT CORRECT
# ----------------------------------------------------
flutter:
  # Doit être aligné avec 'dependencies:', et indenté avec DEUX ESPACES.
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/timeismoney-text-appbar.png
    - assets/images/timeismoney-text-splash-screen.png
    - pubspec.yaml

# Configuration pour la génération des icônes
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_android: false
  remove_alpha_ios: false
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  linux:
    generate: true
    image_path: "assets/images/app_icon.png"

# Configuration du nom de l'application pour toutes les plateformes
flutter_launcher_name:
  name: "Time Is Money"