name: timeismoney
description: Application ludique et utilitaire pour visualiser en temps réel l'argent que l'on gagne.
publish_to: 'none'
version: 1.3.0+141025

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.4.0
  flutter_lints: ^2.0.0
  intl: ^0.18.1
  package_info_plus: ^4.0.0

  # Vos dépendances de packages
  provider: ^6.1.1 
  shared_preferences: ^2.3.2 

  # Optional: if you want to render SVG assets directly in Flutter widgets
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# ----------------------------------------------------
#  NOUVELLE SECTION ET EMPLACEMENT CORRECT
# ----------------------------------------------------
flutter:
  # Doit être aligné avec 'dependencies:', et indenté avec DEUX ESPACES.
  uses-material-design: true
  assets:
    - assets/images/hourglass.svg
    - assets/images/app_icon.png
    - pubspec.yaml

# Configuration pour la génération des icônes
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  linux:
    generate: true
    image_path: "assets/images/app_icon.png"