name: timeismoney
description: Application ludique et utilitaire pour visualiser en temps réel l'argent que l'on gagne.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0 # <--- VÉRIFIEZ QUE CETTE LIGNE EST PRÉSENTE

  # Vos dépendances de packages
  provider: ^6.1.1 
  shared_preferences: ^2.2.2 

dev_dependencies:
  # ... (Vos dev_dependencies) ...

# ----------------------------------------------------
#  NOUVELLE SECTION ET EMPLACEMENT CORRECT
# ----------------------------------------------------
flutter:
  # Doit être aligné avec 'dependencies:', et indenté avec DEUX ESPACES.
  uses-material-design: true