name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    # 1. Récupère ton code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. Récupère le numéro de version depuis le tag
    - name: Get version from tag
      id: get_version
      run: |
        $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "VERSION=$VERSION" >> $env:GITHUB_OUTPUT
        echo "Version détectée: $VERSION"
      shell: pwsh
    
    # 3. Setup Java pour Android
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    # 4. Installe Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: stable
    
    # 5. Installe les dépendances
    - name: Install dependencies
      run: flutter pub get
    
    # 6. Build Windows
    - name: Build Windows Release
      run: flutter build windows --release
    
    # 7. Copie les DLL nécessaires dans le build
    - name: Copy required DLLs
      run: |
        New-Item -ItemType Directory -Force -Path "build/windows/x64/runner/Release/dll"
        if (Test-Path "dll/*.dll") {
          Copy-Item -Path "dll/*.dll" -Destination "build/windows/x64/runner/Release/" -Force
          echo "DLLs copiées avec succès"
        } else {
          echo "⚠️ Aucune DLL trouvée dans le dossier dll/"
        }
      shell: pwsh
    
    # 8. Compresse le build Windows avec version dans le nom
    - name: Archive Windows Build
      run: |
        $VERSION = "${{ steps.get_version.outputs.VERSION }}"
        cd build/windows/x64/runner/Release
        Compress-Archive -Path * -DestinationPath "../../../../../TimeIsMoney-Windows-v$VERSION.zip"
        echo "Archive créée: TimeIsMoney-Windows-v$VERSION.zip"
      shell: pwsh
    
    # 9. Build Android APK
    - name: Clean Flutter build for Android
      run: flutter clean
      
    - name: Get Flutter dependencies for Android
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release --verbose
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
    
    # 10. Renomme l'APK avec la version
    - name: Rename APK with version
      run: |
        $VERSION = "${{ steps.get_version.outputs.VERSION }}"
        Copy-Item build/app/outputs/flutter-apk/app-release.apk -Destination "TimeIsMoney-v$VERSION.apk"
        echo "APK créé: TimeIsMoney-v$VERSION.apk"
      shell: pwsh
    
    # 11. Crée la Release GitHub
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          TimeIsMoney-Windows-v${{ steps.get_version.outputs.VERSION }}.zip
          TimeIsMoney-v${{ steps.get_version.outputs.VERSION }}.apk
        body: |
          ## ⏱️ Time Is Money v${{ steps.get_version.outputs.VERSION }}
          
          ### 📥 Téléchargements
          - **Windows** : `TimeIsMoney-Windows-v${{ steps.get_version.outputs.VERSION }}.zip`
          - **Android** : `TimeIsMoney-v${{ steps.get_version.outputs.VERSION }}.apk`
          
          ### ⚙️ Installation Windows
          1. Extraire le fichier ZIP
          2. Lancer `timeismoney.exe`
          3. Les DLLs Visual C++ nécessaires sont incluses dans le package
          
          ### 📱 Installation Android
          1. Activer "Sources inconnues" dans les paramètres
          2. Installer l'APK
          
          ### 📝 Changements
          Voir le [CHANGELOG.txt](https://github.com/WolwX/timeismoney/blob/main/CHANGELOG.txt)
          
          ### 🔧 DLLs incluses (Windows)
          - msvcp140.dll
          - vcruntime140.dll
          - vcruntime140_1.dll
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}